# DB_NAME
# DB_USER
# DB_PASSWORD
# DB_HOST
# DB_PORT
$env:SECRET_KEY="idfghslkhjgoseirjtsoiejtoisjrlikthjgallketjzeskl"

# EMAIL_HOST
# EMAIL_PORT
# EMAIL_HOST_USER
# EMAIL_HOST_PASSWORD
# EMAIL_SENDER
# EMAIL_SENDER_NAME
# EMAIL_EVENT_NAME
# EMAIL_REPLY_TO
# EMAIL_USE_TLS