# Generated by Django 4.2.3 on 2023-09-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosksvc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='checkInCode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
