# Generated by Django 4.2.3 on 2023-09-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosksvc', '0002_participant_checkincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='checkInCode',
        ),
        migrations.AddField(
            model_name='participant',
            name='passCode',
            field=models.BinaryField(max_length=100, null=True),
        ),
    ]
