# Generated by Django 4.2.3 on 2023-09-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosksvc', '0003_remove_participant_checkincode_participant_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='couponDetail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
