# Generated by Django 4.2.3 on 2023-09-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosksvc', '0004_participant_coupondetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='couponDetail',
            field=models.CharField(default='', max_length=200),
        ),
    ]
